# Generated by Django 3.1.5 on 2021-04-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='S_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=100)),
                ('subject2', models.CharField(max_length=100)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='S_Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1_marks', models.IntegerField(max_length=3)),
                ('date', models.DateField(auto_now=True)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.s_subjects')),
            ],
        ),
    ]
